apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi2
  template:
    metadata:
      labels:
        app: fastapi2
    spec:
      containers:
        - name: fastapi2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@my-release-postgresql:5432/postgres"
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 80
