apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi2
  template:
    metadata:
      labels:
        app: fastapi2
    spec:
      containers:
        - name: fastapi2
          image: "fastapi-postgres-crud:5"
          imagePullPolicy: Never
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:prSnRMFQff@my-release-postgresql:5432/postgres"
          ports:
            - containerPort: 80
