apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-postgres-crud:3
          imagePullPolicy: Never
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:password@postgres:5432/mydatabase"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: NodePort  
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80