remoteWrite:
  - url: "http://vm-victoria-metrics-single-server.default.svc.cluster.local:8428/api/v1/write"

scrape:
  enabled: true
  extraScrapeConfigs:
  scrape_configs:
    - job_name: "fastapi"
      metrics_path: /metrics
      static_configs:
        - targets: ["192.168.49.2:30317"]  # Your FastAPI NodePort IP and Port

