remoteWrite:
  - url: "http://vm-victoria-metrics-single-server.default.svc.cluster.local:8428/api/v1/write"

scrape:
  enabled: true
  scrape_configs:
    - job_name: "fastapi"
      static_configs:
        - targets: ["192.168.49.2:30317"]