apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi2
  template:
    metadata:
      labels:
        app: fastapi2
    spec:
      containers:
        - name: fastapi2
          image: farahdiouani/fastapi-postgres-crud:latest  
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:password@192.168.1.140:5432/mydatabase"
          ports:
            - containerPort: 80
