apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres2
  template:
    metadata:
      labels:
        app: postgres2
    spec:
      containers:
        - name: postgres2
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mydatabase"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc